// Code generated by goxc from main.gox. DO NOT EDIT.

//line main.gox:1
//go:generate go run github.com/rknit/tui.gox/cmd/goxc .

package main; import gox "github.com/rknit/tui.gox/gox"

import (
	"fmt"
	"os"
)

type CounterProps struct {
	Label string
	Step  int
}

func Counter(p CounterProps) gox.Node {
	count, setCount := gox.UseState(0)
	return (
		gox.C(gox.Box, gox.BoxProps{Direction: "row", Gap: 2, Border: "rounded", PaddingX: 1, Title: p.Label, 
Children: gox.F(gox.C(gox.Text, gox.TextProps{
Children: gox.F("Count: ", gox.C(gox.Span, gox.SpanProps{Bold: true, Color: "10", Children: count}),
)}), 
gox.C(gox.Spacer, gox.SpacerProps{}), 
gox.C(gox.Button, gox.ButtonProps{OnPress: func() { setCount(count - p.Step) }, Children: gox.F("-", p.Step)}), 
gox.C(gox.Button, gox.ButtonProps{OnPress: func() { setCount(count + p.Step) }, AutoFocus: true, Children: gox.F("+", p.Step)}),
)}))
}

func App() gox.Node {
	app := gox.UseApp()
	gox.UseInput(func(k gox.Key) bool {
		if k.String() == "q" {
			app.Quit()
			return true
		}
		return false
	})
	return (
		gox.C(gox.Box, gox.BoxProps{Padding: 1, Gap: 1, 
Children: gox.F(gox.C(gox.Text, gox.TextProps{Bold: true, Color: "12", Children: "gox counter"}), 
gox.C(Counter, CounterProps{Label: "Ones", Step: 1}), 
gox.C(Counter, CounterProps{Label: "Tens", Step: 10}), 
gox.C(gox.Text, gox.TextProps{Faint: true, Children: "tab/shift+tab to move focus, enter to press, q to quit"}),
)}))
}

func main() {
	if err := gox.Run(gox.C0(App)); err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
}
