// Code generated by goxc from main.gox. DO NOT EDIT.

//line main.gox:1
//go:generate go run github.com/rknit/tui.gox/cmd/goxc .

package main; import gox "github.com/rknit/tui.gox/gox"

import (
	"fmt"
	"os"
	"time"

	"github.com/charmbracelet/bubbles/textarea"
	tea "github.com/charmbracelet/bubbletea"
)

// Panel is a reusable bordered section. Box lets callers pass any layout
// props, which are spread onto the underlying <box>.
type PanelProps struct {
	Title    string
	Box      gox.BoxProps
	Children gox.Node
}

func Panel(p PanelProps) gox.Node {
	return (
		gox.C(gox.Box, func() (gox_spread_ gox.BoxProps) { gox_spread_ = (p.Box); gox_spread_.Border = "rounded"; gox_spread_.BorderColor = "8"; gox_spread_.Title = p.Title; gox_spread_.PaddingX = 1; 
gox_spread_.Children = p.Children; 
return }()))
}

// List is a generic component: <List[T] items={...} render={...} />.
type ListProps[T any] struct {
	Items  []T
	Render func(item T, index int) gox.Node
}

func List[T any](p ListProps[T]) gox.Node {
	return gox.F(gox.Map(p.Items, p.Render))
}

// Log appends a line every half second into a scroll viewport that follows
// the bottom until you scroll up (wheel, or focus it and use arrows).
func Log() gox.Node {
	lines, setLines := gox.UseState([]string{"started"})
	gox.UseInterval(500*time.Millisecond, func() {
		setLines(append(lines, fmt.Sprintf("%s tick %d", time.Now().Format("15:04:05"), len(lines))))
	})
	return (
		gox.C(gox.Scroll, gox.ScrollProps{Height: 4, FollowBottom: true, 
Children: gox.C(List[string], ListProps[string]{Items: lines, Render: func(l string, i int) gox.Node {
				return gox.K(i, gox.C(gox.Text, gox.TextProps{Faint: i%2 == 1, Children: l}))
			}}),
}))
}

// Download simulates background work updating state from a goroutine.
func Download() gox.Node {
	progress, setProgress := gox.UseState(0.0)
	running, setRunning := gox.UseState(false)

	gox.UseEffect(func() func() {
		if !running {
			return nil
		}
		stop := make(chan struct{})
		go func() {
			for p := 0.0; p <= 1.0001; p += 0.05 {
				select {
				case <-stop:
					return
				case <-time.After(100 * time.Millisecond):
					setProgress(p)
				}
			}
			setRunning(false)
		}()
		return func() { close(stop) }
	}, running)

	return (
		gox.F(
gox.C(gox.Show, gox.ShowProps{When: running, Fallback: gox.C(gox.Text, gox.TextProps{Color: "10", Children: gox.IfElse(progress >= 1, "✓ done", "idle")}), 
Children: gox.C(gox.Spinner, gox.SpinnerProps{Color: "13", Children: "downloading…"}),
}), 
gox.C(gox.Progress, gox.ProgressProps{Value: progress, Width: 24, Color: "13", ShowPercent: true}), 
gox.C(gox.Button, gox.ButtonProps{Disabled: running, OnPress: func() { setProgress(0); setRunning(true) }, Children: "start"}),
))
}

var flavors = []string{"Vanilla", "Chocolate", "Strawberry", "Mint", "Pistachio", "Mango"}

func App() gox.Node {
	app := gox.UseApp()
	w, h := gox.UseWindowSize()
	flavor, setFlavor := gox.UseState(0)
	chosen, setChosen := gox.UseState(-1)
	name, setName := gox.UseState("")
	notes, setNotes := gox.UseState("")
	subscribe, setSubscribe := gox.UseState(true)

	gox.UseInput(func(k gox.Key) bool {
		if k.String() == "esc" {
			app.Quit()
			return true
		}
		return false
	})

	ta := gox.UseMemo(func() tea.Model {
		t := textarea.New()
		t.Placeholder = "Embedded bubbles/textarea…"
		t.SetWidth(30)
		t.SetHeight(3)
		t.Focus()
		return gox.Bubble(t)
	})

	return (
		gox.C(gox.Box, gox.BoxProps{Padding: 1, Gap: 1, 
Children: gox.F(gox.C(gox.Box, gox.BoxProps{Direction: "row", 
Children: gox.F(gox.C(gox.Text, gox.TextProps{Bold: true, Color: "12", Children: "gox showcase"}), 
gox.C(gox.Spacer, gox.SpacerProps{}), 
gox.C(gox.Text, gox.TextProps{Faint: true, Children: gox.F(w, "×", h, " · tab/mouse to focus · esc to quit")}),
)}), 
gox.C(gox.Box, gox.BoxProps{Direction: "row", Gap: 1, 
Children: gox.F(gox.C(Panel, PanelProps{Title: "Form", Box: gox.BoxProps{Grow: 1}, 
Children: gox.F(gox.C(gox.Input, gox.InputProps{Value: name, OnChange: setName, Prompt: "Name: ", Placeholder: "Ada", AutoFocus: true}), 
gox.C(gox.Checkbox, gox.CheckboxProps{Checked: subscribe, OnChange: setSubscribe, Children: "subscribe"}), 
gox.C(gox.Text, gox.TextProps{Children: "Flavor:"}), 
gox.C(gox.Select, gox.SelectProps{Options: flavors, Index: flavor, OnChange: setFlavor, OnSelect: setChosen, Height: 4}),
)}), 
gox.C(Panel, PanelProps{Title: "Async", Box: gox.BoxProps{Grow: 1, Gap: 1}, 
Children: gox.F(gox.C0(Download), 
gox.C0(Log),
)}),
)}), 
gox.C(Panel, PanelProps{Title: "Bubble Tea interop", 
Children: gox.C(gox.Model, gox.ModelProps{Model: ta, OnChange: func(m tea.Model) { setNotes(gox.Unwrap[textarea.Model](m).Value()) }}),
}), 
gox.C(gox.Divider, gox.DividerProps{Title: "summary", Color: "8"}), 
gox.C(gox.Text, gox.TextProps{
Children: gox.F("Hello ", gox.C(gox.Span, gox.SpanProps{Bold: true, Children: gox.IfElse(name == "", "stranger", name)}), 
gox.If(chosen >= 0, fmt.Sprintf(", you picked %s", flavors[max(chosen, 0)])), 
gox.If(subscribe, " (subscribed)"), ". Notes: ", len(notes), " chars.",
)}),
)}))
}

func main() {
	if err := gox.Run(gox.C0(App), gox.WithAltScreen(), gox.WithMouse()); err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
}
