package transpile

import (
	"bytes"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// GeneratedPrefix starts every file generated by goxc.
const GeneratedPrefix = "// Code generated by goxc"

// OutputName maps foo.gox to foo_gox.go and foo_test.gox to foo_gox_test.go.
func OutputName(path string) string {
	base := strings.TrimSuffix(path, ".gox")
	if b, ok := strings.CutSuffix(base, "_test"); ok {
		return b + "_gox_test.go"
	}
	return base + "_gox.go"
}

// SourceName maps a generated file name back to its .gox file name, or ""
// if the name is not a generated file name.
func SourceName(path string) string {
	if b, ok := strings.CutSuffix(path, "_gox_test.go"); ok {
		return b + "_test.gox"
	}
	if b, ok := strings.CutSuffix(path, "_gox.go"); ok {
		return b + ".gox"
	}
	return ""
}

// Package is a directory's .gox sources with the component signatures
// declared across its .go and .gox files.
type Package struct {
	Dir string
	// Files maps .gox paths to their sources, sorted in Paths.
	Files map[string][]byte
	Paths []string
	Sigs  map[string]Signature
}

// LoadPackage reads the .gox and .go files of dir. overlay maps file paths to
// contents that replace (or add to) the files on disk, e.g. unsaved editor
// buffers. Generated files are ignored. .gox files that fail to transpile do
// not contribute signatures.
func LoadPackage(dir string, overlay map[string][]byte) (*Package, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}
	pkg := &Package{Dir: dir, Files: map[string][]byte{}, Sigs: map[string]Signature{}}
	goFiles := map[string][]byte{}
	for _, e := range entries {
		name := e.Name()
		path := filepath.Join(dir, name)
		if e.IsDir() || !(strings.HasSuffix(name, ".gox") || strings.HasSuffix(name, ".go")) {
			continue
		}
		if _, ok := overlay[path]; ok {
			continue
		}
		src, err := os.ReadFile(path)
		if err != nil {
			return nil, err
		}
		if strings.HasSuffix(name, ".gox") {
			pkg.Files[path] = src
		} else {
			goFiles[path] = src
		}
	}
	for path, src := range overlay {
		if filepath.Dir(path) != filepath.Clean(dir) {
			continue
		}
		switch {
		case strings.HasSuffix(path, ".gox"):
			pkg.Files[path] = src
		case strings.HasSuffix(path, ".go"):
			goFiles[path] = src
		}
	}
	for _, src := range goFiles {
		if !bytes.HasPrefix(src, []byte(GeneratedPrefix)) {
			CollectSignatures(src, pkg.Sigs)
		}
	}
	for path := range pkg.Files {
		pkg.Paths = append(pkg.Paths, path)
	}
	sort.Strings(pkg.Paths)
	for _, path := range pkg.Paths {
		if out, err := Transpile(pkg.Files[path], Options{Filename: path}); err == nil {
			CollectSignatures(out, pkg.Sigs)
		}
	}
	return pkg, nil
}

// Transpile generates the Go code of one of the package's .gox files.
func (p *Package) Transpile(path string) ([]byte, *SourceMap, error) {
	return TranspileMap(p.Files[path], Options{Filename: path, Components: p.Sigs})
}

// PropsType returns the props type expression of the component referenced by
// tag (as written in a .gox file), qualified for runtime package rt.
func PropsType(tag string, sigs map[string]Signature, rt string) (props string, ok bool) {
	defer func() {
		if recover() != nil {
			props, ok = "", false
		}
	}()
	t := &transpiler{opts: Options{Components: sigs}, rt: rt}
	_, props, noProps := t.resolve(tag, 0)
	return props, !noProps && props != ""
}

// FieldName returns the props field an attribute name refers to
// (onPress -> OnPress, on-press -> OnPress).
func FieldName(attr string) string { return fieldName(attr) }

// ClosingTag returns the text to insert for automatic tag closing at offset
// in src, or "" when nothing should be inserted.
//
// Just after typing '>' that completes an opening tag, it returns the
// closing tag ("</box>"), unless the document is already balanced. Just
// after typing "</", it returns the rest of the innermost open tag ("box>").
func ClosingTag(src []byte, offset int) string {
	if offset < 1 || offset > len(src) {
		return ""
	}
	after := src[offset:]
	switch {
	case offset >= 2 && string(src[offset-2:offset]) == "</":
		el := innermostOpen(src[:offset-2])
		if el == nil {
			return ""
		}
		text := el.name + ">"
		if bytes.HasPrefix(after, []byte(text)) {
			return ""
		}
		return text
	case src[offset-1] == '>':
		el := innermostOpen(src[:offset])
		if el == nil || el.tagEnd != offset {
			return ""
		}
		text := "</" + el.name + ">"
		if bytes.HasPrefix(after, []byte(text)) {
			return ""
		}
		if _, err := Transpile(src, Options{}); err == nil {
			return "" // already balanced: editing an existing tag
		}
		return text
	}
	return ""
}

// innermostOpen returns the innermost element that src leaves unclosed.
func innermostOpen(src []byte) (el *openElement) {
	t := &transpiler{src: src, rt: "gox", opts: Options{Filename: "input.gox"}}
	defer func() {
		if r := recover(); r != nil {
			if _, ok := r.(*Error); !ok {
				panic(r)
			}
			el = t.open
		}
	}()
	t.goCode(0, false)
	return nil
}
