// Package transpile converts .gox source (Go with embedded XML elements, in
// the spirit of TSX) into plain Go source that targets the gox runtime.
//
// The runtime package is imported automatically as "gox" when a file uses
// elements or refers to gox.X and does not import it itself.
//
// Element rules:
//
//	<box ...>          built-in tag   -> gox.C(gox.Box, gox.BoxProps{...})
//	<Card ...>         component      -> gox.C(Card, CardProps{...})
//	<card ...>         lowercase local component (not a built-in) -> gox.C(card, cardProps{...})
//	<ui.Card ...>      qualified      -> gox.C(ui.Card, ui.CardProps{...})
//	<>...</>           fragment       -> gox.F(...)
//	key={k}            special        -> gox.K(k, <element>)
//
// Attribute names are capitalized to form the Go field name (onPress -> OnPress).
// Children are passed through the Children field of the props struct.
//
// The generated code keeps every source line on the same output line so that
// a //line directive maps compiler errors back to the .gox file.
package transpile

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"html"
	"strconv"
	"strings"
	"unicode"
	"unicode/utf8"
)

// RuntimeImport is the import path of the gox runtime.
const RuntimeImport = "github.com/rknit/tui.gox/gox"

// Signature describes how a component function is called.
type Signature struct {
	// TypeParams lists the type parameter names of a generic component.
	TypeParams []string
	// NoProps is true for components declared as func() gox.Node.
	NoProps bool
	// PropsType is the Go type expression of the single props parameter.
	PropsType string
}

// Options configure a transpilation.
type Options struct {
	// Filename is used for error messages and the //line directive.
	Filename string
	// Components maps component names declared in the same package to their
	// signatures. Unknown components fall back to the <Name>Props convention.
	Components map[string]Signature
}

// Error is a positioned transpilation error.
type Error struct {
	Filename  string
	Line, Col int
	Msg       string
}

func (e *Error) Error() string {
	return fmt.Sprintf("%s:%d:%d: %s", e.Filename, e.Line, e.Col, e.Msg)
}

// Transpile converts .gox source into Go source.
func Transpile(src []byte, opts Options) (out []byte, err error) {
	if opts.Filename == "" {
		opts.Filename = "input.gox"
	}
	t := &transpiler{src: src, opts: opts, rt: "gox"}

	alias, imported, insertAt := runtimeAlias(src)
	if imported {
		t.rt = alias
	}

	defer func() {
		if r := recover(); r != nil {
			if e, ok := r.(*Error); ok {
				out, err = nil, e
				return
			}
			panic(r)
		}
	}()

	body := t.goCode(0, false)

	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by goxc from %s. DO NOT EDIT.\n\n", baseName(opts.Filename))
	fmt.Fprintf(&b, "//line %s:1\n", baseName(opts.Filename))
	if t.used && !imported && insertAt >= 0 {
		// Insert the import on the package clause line to keep lines aligned.
		b.WriteString(body[:insertAt])
		fmt.Fprintf(&b, "; import %s %q", t.rt, RuntimeImport)
		b.WriteString(body[insertAt:])
	} else {
		b.WriteString(body)
	}
	return b.Bytes(), nil
}

func baseName(p string) string {
	if i := strings.LastIndexAny(p, `/\`); i >= 0 {
		return p[i+1:]
	}
	return p
}

// runtimeAlias finds how the runtime package is imported and where an import
// can be inserted (end of the package clause).
func runtimeAlias(src []byte) (alias string, imported bool, insertAt int) {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, "", src, parser.ImportsOnly)
	if f == nil || f.Name == nil {
		return "", false, -1
	}
	_ = err
	insertAt = fset.Position(f.Name.End()).Offset
	for _, imp := range f.Imports {
		p, _ := strconv.Unquote(imp.Path.Value)
		if p != RuntimeImport {
			continue
		}
		if imp.Name != nil {
			return imp.Name.Name, true, insertAt
		}
		return "gox", true, insertAt
	}
	return "", false, insertAt
}

type transpiler struct {
	src  []byte
	opts Options
	rt   string // runtime package identifier
	used bool
	end  int // position after the last parsed construct
}

func (t *transpiler) fail(pos int, format string, args ...any) {
	line, col := t.lineCol(pos)
	panic(&Error{Filename: t.opts.Filename, Line: line, Col: col, Msg: fmt.Sprintf(format, args...)})
}

func (t *transpiler) lineCol(pos int) (int, int) {
	if pos > len(t.src) {
		pos = len(t.src)
	}
	line := 1 + bytes.Count(t.src[:pos], []byte{'\n'})
	col := pos - bytes.LastIndexByte(t.src[:pos], '\n')
	return line, col
}

// ---------------------------------------------------------------------------
// Go mode

type tokKind int

const (
	tkNone    tokKind = iota // start of input / after a separator
	tkOperand                // identifier, literal, ) ] }
	tkOther                  // operator, keyword, opening punctuation
)

var operandKeywords = map[string]bool{
	"break": true, "continue": true, "fallthrough": true,
}

var goKeywords = map[string]bool{
	"break": true, "case": true, "chan": true, "const": true, "continue": true,
	"default": true, "defer": true, "else": true, "fallthrough": true, "for": true,
	"func": true, "go": true, "goto": true, "if": true, "import": true,
	"interface": true, "map": true, "package": true, "range": true, "return": true,
	"select": true, "struct": true, "switch": true, "type": true, "var": true,
}

// goCode copies Go source starting at pos, replacing XML elements with
// generated calls. When inBrace is set, it stops at the unmatched closing
// brace (which is consumed but not emitted). It returns the generated code;
// the end position is stored in t.pos.
func (t *transpiler) goCode(pos int, inBrace bool) string {
	var out strings.Builder
	src := t.src
	depth := 0
	prev := tkNone
	start := pos

	for pos < len(src) {
		c := src[pos]
		switch {
		case c == '\n':
			out.WriteByte(c)
			pos++
			if prev == tkOperand {
				prev = tkNone // automatic semicolon
			}
		case c == ' ' || c == '\t' || c == '\r':
			out.WriteByte(c)
			pos++
		case c == '/' && pos+1 < len(src) && src[pos+1] == '/':
			end := bytes.IndexByte(src[pos:], '\n')
			if end < 0 {
				end = len(src) - pos
			}
			out.Write(src[pos : pos+end])
			pos += end
		case c == '/' && pos+1 < len(src) && src[pos+1] == '*':
			end := bytes.Index(src[pos+2:], []byte("*/"))
			if end < 0 {
				t.fail(pos, "unterminated comment")
			}
			out.Write(src[pos : pos+2+end+2])
			pos += 2 + end + 2
		case c == '"' || c == '\'' || c == '`':
			end := t.skipQuoted(pos)
			out.Write(src[pos:end])
			pos = end
			prev = tkOperand
		case c == '{' || c == '(' || c == '[':
			if c == '{' {
				depth++
			}
			out.WriteByte(c)
			pos++
			prev = tkOther
		case c == '}':
			if inBrace && depth == 0 {
				t.end = pos + 1
				return out.String()
			}
			depth--
			out.WriteByte(c)
			pos++
			prev = tkOperand
		case c == ')' || c == ']':
			out.WriteByte(c)
			pos++
			prev = tkOperand
		case c == '<' && prev != tkOperand && t.startsElement(pos):
			code := t.element(pos, true)
			out.WriteString(code)
			pos = t.end
			prev = tkOperand
		case isIdentStart(src, pos):
			end := identEnd(src, pos)
			word := string(src[pos:end])
			out.WriteString(word)
			pos = end
			start := pos - len(word)
			if word == t.rt && pos < len(src) && src[pos] == '.' && (start == 0 || src[start-1] != '.') {
				t.used = true // explicit gox.X reference: import is implied
			}
			if goKeywords[word] && !operandKeywords[word] {
				prev = tkOther
			} else {
				prev = tkOperand
			}
		case c >= '0' && c <= '9' || (c == '.' && pos+1 < len(src) && src[pos+1] >= '0' && src[pos+1] <= '9'):
			end := pos
			for end < len(src) && (isAlnum(src[end]) || src[end] == '.' ||
				((src[end] == '+' || src[end] == '-') && end > pos && strings.ContainsRune("eEpP", rune(src[end-1])))) {
				end++
			}
			out.Write(src[pos:end])
			pos = end
			prev = tkOperand
		default:
			// Operators and other punctuation. ++ and -- end an operand.
			if (c == '+' || c == '-') && pos+1 < len(src) && src[pos+1] == c {
				out.Write(src[pos : pos+2])
				pos += 2
				prev = tkOperand
				continue
			}
			out.WriteByte(c)
			pos++
			if c == '<' { // <<, <=, <-, <<=
				for pos < len(src) && (src[pos] == '<' || src[pos] == '=' || src[pos] == '-') {
					out.WriteByte(src[pos])
					pos++
				}
			}
			prev = tkOther
		}
	}
	if inBrace {
		t.fail(start, "unterminated expression: missing '}'")
	}
	t.end = pos
	return out.String()
}

func (t *transpiler) startsElement(pos int) bool {
	if pos+1 >= len(t.src) {
		return false
	}
	n := t.src[pos+1]
	return n == '>' || isIdentStart(t.src, pos+1)
}

func (t *transpiler) skipQuoted(pos int) int {
	src := t.src
	q := src[pos]
	i := pos + 1
	for i < len(src) {
		switch src[i] {
		case '\\':
			if q != '`' {
				i += 2
				continue
			}
		case '\n':
			if q != '`' {
				t.fail(pos, "unterminated literal")
			}
		case q:
			return i + 1
		}
		i++
	}
	t.fail(pos, "unterminated literal")
	return 0
}

func isIdentStart(src []byte, pos int) bool {
	r, _ := utf8.DecodeRune(src[pos:])
	return r == '_' || unicode.IsLetter(r)
}

func identEnd(src []byte, pos int) int {
	for pos < len(src) {
		r, size := utf8.DecodeRune(src[pos:])
		if r != '_' && !unicode.IsLetter(r) && !unicode.IsDigit(r) {
			break
		}
		pos += size
	}
	return pos
}

func isAlnum(c byte) bool {
	return c == '_' || c >= '0' && c <= '9' || c >= 'a' && c <= 'z' || c >= 'A' && c <= 'Z'
}

// ---------------------------------------------------------------------------
// XML mode

type attr struct {
	name  string
	value string // Go expression
	pos   int
}

type child struct {
	code string
	pos  int
}

// element parses the element starting at pos ('<') and returns Go code.
// t.end is set to the position after the element. For a top-level element
// followed by a newline and ')', the newline is moved inside the generated
// call so Go's semicolon insertion does not break `return (\n<x/>\n)`.
func (t *transpiler) element(pos int, top bool) string {
	t.used = true
	start := pos
	pos++ // '<'

	// Fragment.
	if t.src[pos] == '>' {
		children, end := t.children(pos+1, "")
		w := newWriter(t, start)
		t.end = t.extend(w, end, top)
		w.str(t.rt + ".F(")
		w.args(children, end)
		w.str(")")
		return w.String()
	}

	name, pos := t.tagName(pos)
	var attrs []attr
	var key, spread *attr
	selfClosing := false
	for {
		pos = t.skipSpace(pos)
		if pos >= len(t.src) {
			t.fail(start, "unterminated element <%s>", name)
		}
		c := t.src[pos]
		if c == '/' {
			if pos+1 >= len(t.src) || t.src[pos+1] != '>' {
				t.fail(pos, "expected '/>'")
			}
			pos += 2
			selfClosing = true
			break
		}
		if c == '>' {
			pos++
			break
		}
		if c == '{' {
			p := t.skipSpace(pos + 1)
			if !bytes.HasPrefix(t.src[p:], []byte("...")) {
				t.fail(pos, "expected spread attribute {...expr}")
			}
			if spread != nil {
				t.fail(pos, "only one spread attribute is allowed")
			}
			if len(attrs) > 0 {
				t.fail(pos, "spread attribute must come before other attributes")
			}
			code := strings.TrimSpace(t.goCode(p+3, true))
			if code == "" {
				t.fail(pos, "empty spread attribute")
			}
			spread = &attr{value: code, pos: pos}
			pos = t.end
			continue
		}
		if !isIdentStart(t.src, pos) {
			t.fail(pos, "unexpected %q in element <%s>", c, name)
		}
		aStart := pos
		aEnd := identEnd(t.src, pos)
		for aEnd < len(t.src) && t.src[aEnd] == '-' { // allow data-like names
			aEnd = identEnd(t.src, aEnd+1)
		}
		aName := string(t.src[aStart:aEnd])
		pos = t.skipSpace(aEnd)
		a := attr{name: aName, pos: aStart, value: "true"}
		if pos < len(t.src) && t.src[pos] == '=' {
			pos = t.skipSpace(pos + 1)
			if pos >= len(t.src) {
				t.fail(aStart, "missing value for attribute %s", aName)
			}
			switch t.src[pos] {
			case '"', '\'':
				q := t.src[pos]
				end := bytes.IndexByte(t.src[pos+1:], q)
				if end < 0 {
					t.fail(pos, "unterminated attribute string")
				}
				raw := string(t.src[pos+1 : pos+1+end])
				a.value = strconv.Quote(html.UnescapeString(raw))
				pos += end + 2
			case '{':
				a.value = strings.TrimSpace(t.goCode(pos+1, true))
				if a.value == "" {
					t.fail(pos, "empty expression for attribute %s", aName)
				}
				pos = t.end
			case '<':
				a.value = t.element(pos, false)
				pos = t.end
			default:
				t.fail(pos, "attribute value must be a string, {expression} or element")
			}
		}
		if aName == "key" {
			if key != nil {
				t.fail(aStart, "duplicate key attribute")
			}
			k := a
			key = &k
			continue
		}
		for _, o := range attrs {
			if o.name == aName {
				t.fail(aStart, "duplicate attribute %s", aName)
			}
		}
		attrs = append(attrs, a)
	}

	var children []child
	end := pos
	if !selfClosing {
		children, end = t.children(pos, name)
	}
	w := newWriter(t, start)
	t.end = t.extend(w, end, top)
	if key != nil {
		w.str(t.rt + ".K(" + key.value + ", ")
	}
	t.call(w, name, start, spread, attrs, children, end)
	if key != nil {
		w.str(")")
	}
	return w.String()
}

func (t *transpiler) call(w *writer, name string, pos int, spread *attr, attrs []attr, children []child, end int) {
	fn, props, noProps := t.resolve(name, pos)
	if noProps {
		if spread != nil || len(attrs) > 0 || len(children) > 0 {
			t.fail(pos, "component %s takes no props", name)
		}
		w.str(t.rt + ".C0(" + fn)
		w.end(end, ")", true)
		return
	}
	w.str(t.rt + ".C(" + fn + ", ")
	if spread != nil {
		t.spreadProps(w, props, spread, attrs, children, end)
		w.str(")")
		return
	}
	if strings.HasPrefix(props, "*") {
		w.str("&" + props[1:] + "{")
	} else {
		w.str(props + "{")
	}
	n := len(attrs)
	if len(children) > 0 {
		n++
	}
	i := 0
	for _, a := range attrs {
		w.sync(a.pos)
		w.str(fieldName(a.name) + ": " + a.value)
		i++
		if i < n {
			w.str(", ")
		}
	}
	if len(children) > 0 {
		w.sync(children[0].pos)
		w.str("Children: ")
		if len(children) == 1 {
			w.str(children[0].code)
			w.end(end, "}", true)
		} else {
			w.str(t.rt + ".F(")
			w.args(children, end)
			w.str(")}")
		}
	} else {
		w.end(end, "}", n > 0)
	}
	w.str(")")
}

// spreadProps emits an immediately-invoked function that copies the spread
// value and assigns the remaining attributes:
//
//	func() (v P) { v = (spread); v.A = 1; return }()
func (t *transpiler) spreadProps(w *writer, props string, spread *attr, attrs []attr, children []child, end int) {
	const v = "gox_spread_"
	if ptr, ok := strings.CutPrefix(props, "*"); ok {
		w.str("func() *" + ptr + " { " + v + " := *(" + spread.value + "); ")
	} else {
		w.str("func() (" + v + " " + props + ") { " + v + " = (" + spread.value + "); ")
	}
	for _, a := range attrs {
		w.sync(a.pos)
		w.str(v + "." + fieldName(a.name) + " = " + a.value + "; ")
	}
	if len(children) > 0 {
		w.sync(children[0].pos)
		w.str(v + ".Children = ")
		if len(children) == 1 {
			w.str(children[0].code)
		} else {
			w.str(t.rt + ".F(")
			w.args(children, end)
			w.str(")")
		}
		w.str("; ")
	}
	ret := "return }()"
	if strings.HasPrefix(props, "*") {
		ret = "return &" + v + " }()"
	}
	w.end(end, ret, false)
}

// resolve maps a tag name to the component function and its props type.
// Intrinsics are the built-in lowercase elements provided by the runtime.
// Other lowercase tags refer to components declared in the same package.
var Intrinsics = map[string]bool{
	"box": true, "text": true, "span": true, "br": true, "spacer": true,
	"divider": true, "hr": true, "show": true, "input": true, "button": true,
	"checkbox": true, "select": true, "spinner": true, "progress": true,
	"model": true, "scroll": true,
}

func (t *transpiler) resolve(tag string, pos int) (fn, props string, noProps bool) {
	name, targs := splitTag(tag)
	if targs != "" {
		if Intrinsics[name] {
			t.fail(pos, "built-in element <%s> does not take type arguments", name)
		}
		sig, ok := t.opts.Components[name]
		switch {
		case !ok:
			return tag, name + "Props[" + targs + "]", false
		case len(sig.TypeParams) == 0:
			t.fail(pos, "component %s is not generic", name)
		case sig.NoProps:
			return tag, "", true
		}
		args := splitTopLevel(targs)
		if len(args) != len(sig.TypeParams) {
			t.fail(pos, "component %s expects %d type argument(s), got %d", name, len(sig.TypeParams), len(args))
		}
		return tag, substitute(sig.PropsType, sig.TypeParams, args), false
	}
	if sig, ok := t.opts.Components[name]; ok && len(sig.TypeParams) > 0 {
		t.fail(pos, "generic component %s needs type arguments: <%s[%s]>", name, name, strings.Join(sig.TypeParams, ", "))
	}
	if Intrinsics[name] {
		if _, local := t.opts.Components[name]; local {
			t.fail(pos, "<%s> is ambiguous: it is a built-in element and component func %s is declared in this package; rename the component", name, name)
		}
		f := fieldName(name)
		return t.rt + "." + f, t.rt + "." + f + "Props", false
	}
	_, known := t.opts.Components[name]
	if !known && t.opts.Components != nil && !strings.Contains(name, ".") && unicode.IsLower(firstRune(name)) {
		t.fail(pos, "unknown element <%s>: not a built-in and no component func %s is declared in this package", name, name)
	}
	if sig, ok := t.opts.Components[name]; ok {
		if sig.NoProps {
			return name, "", true
		}
		if sig.PropsType != "" {
			return name, sig.PropsType, false
		}
	}
	return name, name + "Props", false
}

func firstRune(s string) rune {
	r, _ := utf8.DecodeRuneInString(s)
	return r
}

func fieldName(attr string) string {
	parts := strings.Split(attr, "-")
	for i, p := range parts {
		r, size := utf8.DecodeRuneInString(p)
		if i > 0 || size > 0 {
			parts[i] = string(unicode.ToUpper(r)) + p[size:]
		}
	}
	return strings.Join(parts, "")
}

func (t *transpiler) tagName(pos int) (string, int) {
	start := pos
	if !isIdentStart(t.src, pos) {
		t.fail(pos, "expected tag name")
	}
	pos = identEnd(t.src, pos)
	for pos < len(t.src) && t.src[pos] == '.' {
		if !isIdentStart(t.src, pos+1) {
			t.fail(pos, "invalid tag name")
		}
		pos = identEnd(t.src, pos+1)
	}
	if pos < len(t.src) && t.src[pos] == '[' { // type arguments: <List[Item]>
		depth := 0
		for ; pos < len(t.src); pos++ {
			switch t.src[pos] {
			case '[', '(':
				depth++
			case ']', ')':
				depth--
			case '\n', '>', '<':
				t.fail(start, "unterminated type arguments in tag")
			}
			if depth == 0 {
				pos++
				break
			}
		}
	}
	return string(t.src[start:pos]), pos
}

func baseOf(name string) string { b, _ := splitTag(name); return b }

// splitTag separates "List[Item]" into "List" and "Item".
func splitTag(name string) (base, args string) {
	if i := strings.IndexByte(name, '['); i >= 0 {
		return name[:i], name[i+1 : len(name)-1]
	}
	return name, ""
}

func (t *transpiler) skipSpace(pos int) int {
	for pos < len(t.src) {
		c := t.src[pos]
		switch {
		case c == ' ' || c == '\t' || c == '\n' || c == '\r':
			pos++
		case c == '/' && pos+1 < len(t.src) && t.src[pos+1] == '/':
			e := bytes.IndexByte(t.src[pos:], '\n')
			if e < 0 {
				return len(t.src)
			}
			pos += e
		case c == '/' && pos+1 < len(t.src) && t.src[pos+1] == '*':
			e := bytes.Index(t.src[pos+2:], []byte("*/"))
			if e < 0 {
				t.fail(pos, "unterminated comment")
			}
			pos += e + 4
		default:
			return pos
		}
	}
	return pos
}

// children parses element content until the closing tag for name ("" for a
// fragment). It returns the children and the position after the closing tag.
func (t *transpiler) children(pos int, name string) ([]child, int) {
	var out []child
	open := pos
	for {
		if pos >= len(t.src) {
			if name == "" {
				t.fail(open, "unterminated fragment")
			}
			t.fail(open, "missing closing tag </%s>", name)
		}
		c := t.src[pos]
		switch c {
		case '<':
			if pos+1 < len(t.src) && t.src[pos+1] == '/' {
				p := t.skipSpace(pos + 2)
				closing := ""
				if p < len(t.src) && t.src[p] != '>' {
					closing, p = t.tagName(p)
				}
				p = t.skipSpace(p)
				if p >= len(t.src) || t.src[p] != '>' {
					t.fail(pos, "expected '>'")
				}
				if cb, _ := splitTag(closing); closing != name && (cb != closing || cb != baseOf(name)) {
					if name == "" {
						t.fail(pos, "expected </> to close fragment, got </%s>", closing)
					}
					t.fail(pos, "expected </%s>, got </%s>", name, closing)
				}
				return out, p + 1
			}
			code := t.element(pos, false)
			out = append(out, child{code: code, pos: pos})
			pos = t.end
		case '{':
			code := t.goCode(pos+1, true)
			if strings.TrimSpace(stripComments(code)) != "" {
				out = append(out, child{code: code, pos: pos + 1})
			}
			pos = t.end
		case '}':
			t.fail(pos, "unexpected '}' in element content; use {\"}\"}")
		default:
			end := pos
			for end < len(t.src) && t.src[end] != '<' && t.src[end] != '{' && t.src[end] != '}' {
				end++
			}
			if text := cleanText(string(t.src[pos:end])); text != "" {
				out = append(out, child{code: strconv.Quote(html.UnescapeString(text)), pos: pos + firstNonSpace(t.src[pos:end])})
			}
			pos = end
		}
	}
}

func firstNonSpace(b []byte) int {
	for i, c := range b {
		if c != ' ' && c != '\t' && c != '\n' && c != '\r' {
			return i
		}
	}
	return 0
}

func stripComments(code string) string {
	var b strings.Builder
	for i := 0; i < len(code); i++ {
		if strings.HasPrefix(code[i:], "//") {
			j := strings.IndexByte(code[i:], '\n')
			if j < 0 {
				break
			}
			i += j
			continue
		}
		if strings.HasPrefix(code[i:], "/*") {
			j := strings.Index(code[i+2:], "*/")
			if j < 0 {
				break
			}
			i += j + 3
			continue
		}
		b.WriteByte(code[i])
	}
	return b.String()
}

// cleanText applies JSX whitespace rules: lines are trimmed, whitespace-only
// lines are dropped, and the remaining lines are joined with single spaces.
func cleanText(s string) string {
	s = strings.ReplaceAll(s, "\r\n", "\n")
	lines := strings.Split(s, "\n")
	lastNonEmpty := -1
	for i, l := range lines {
		if strings.TrimSpace(l) != "" {
			lastNonEmpty = i
		}
	}
	var b strings.Builder
	for i, l := range lines {
		l = strings.ReplaceAll(l, "\t", " ")
		if i != 0 {
			l = strings.TrimLeft(l, " ")
		}
		if i != len(lines)-1 {
			l = strings.TrimRight(l, " ")
		}
		if l == "" {
			continue
		}
		if i != lastNonEmpty {
			l += " "
		}
		b.WriteString(l)
	}
	return b.String()
}

// ---------------------------------------------------------------------------
// writer emits generated code and inserts newlines at safe points (after an
// opening brace/paren or a comma) to keep output lines aligned with source.
// Invariant: generation of an element starts on the source line of its '<'.

type writer struct {
	t      *transpiler
	b      strings.Builder
	base   int // source line of the element start
	out    int // newlines emitted so far
	extend int // line the element's closers must reach (0 for none)
}

// extend checks whether a top-level element ending at end is followed by
// whitespace containing a newline and then ')'. If so, the writer is told to
// end on the line of the ')' and the whitespace is skipped.
func (t *transpiler) extend(w *writer, end int, top bool) int {
	if !top {
		return end
	}
	i, nl := end, false
	for i < len(t.src) && strings.IndexByte(" \t\r\n", t.src[i]) >= 0 {
		nl = nl || t.src[i] == '\n'
		i++
	}
	if !nl || i >= len(t.src) || t.src[i] != ')' {
		return end
	}
	w.extend, _ = t.lineCol(i)
	return i
}

func newWriter(t *transpiler, start int) *writer {
	line, _ := t.lineCol(start)
	return &writer{t: t, base: line}
}

func (w *writer) String() string { return w.b.String() }

func (w *writer) str(s string) {
	w.b.WriteString(s)
	w.out += strings.Count(s, "\n")
}

// sync inserts newlines so that subsequent output lands on the source line of
// pos. It must only be called at a safe point.
func (w *writer) sync(pos int) {
	target, _ := w.t.lineCol(pos)
	for w.base+w.out < target {
		w.b.WriteByte('\n')
		w.out++
	}
}

// args writes a comma separated child list, then the closing sync.
func (w *writer) args(children []child, end int) {
	for i, c := range children {
		w.sync(c.pos)
		w.str(c.code)
		if i < len(children)-1 {
			w.str(", ")
		}
	}
	w.end(end, "", len(children) > 0)
}

// end syncs to the line of the closing tag (end is the position after it),
// adding a trailing comma after items when newlines are needed, then writes
// closer.
func (w *writer) end(end int, closer string, items bool) {
	target, _ := w.t.lineCol(end - 1)
	target = max(target, w.extend)
	if w.base+w.out < target {
		if items {
			w.b.WriteString(",")
		}
		w.sync(end - 1)
	}
	w.str(closer)
}

// ---------------------------------------------------------------------------
// Package scanning

// CollectSignatures extracts top-level component signatures from Go source:
// functions returning a Node with zero parameters or exactly one parameter.
func CollectSignatures(src []byte, into map[string]Signature) {
	fset := token.NewFileSet()
	f, _ := parser.ParseFile(fset, "", src, parser.SkipObjectResolution)
	if f == nil {
		return
	}
	for _, d := range f.Decls {
		fd, ok := d.(*ast.FuncDecl)
		if !ok || fd.Recv != nil || fd.Type.Results == nil || len(fd.Type.Results.List) != 1 {
			continue
		}
		res := fd.Type.Results.List[0].Type
		if !strings.HasSuffix(string(src[fset.Position(res.Pos()).Offset:fset.Position(res.End()).Offset]), "Node") {
			continue
		}
		var tparams []string
		if fd.Type.TypeParams != nil {
			for _, f := range fd.Type.TypeParams.List {
				for _, n := range f.Names {
					tparams = append(tparams, n.Name)
				}
			}
		}
		params := fd.Type.Params.List
		switch {
		case len(params) == 0:
			into[fd.Name.Name] = Signature{NoProps: true, TypeParams: tparams}
		case len(params) == 1 && len(params[0].Names) <= 1:
			typ := params[0].Type
			into[fd.Name.Name] = Signature{TypeParams: tparams, PropsType: string(src[fset.Position(typ.Pos()).Offset:fset.Position(typ.End()).Offset])}
		}
	}
}

// splitTopLevel splits a comma separated list, ignoring nested brackets.
func splitTopLevel(s string) []string {
	var out []string
	depth, start := 0, 0
	for i, c := range s {
		switch c {
		case '[', '(', '{':
			depth++
		case ']', ')', '}':
			depth--
		case ',':
			if depth == 0 {
				out = append(out, strings.TrimSpace(s[start:i]))
				start = i + 1
			}
		}
	}
	return append(out, strings.TrimSpace(s[start:]))
}

// substitute replaces type parameter identifiers in typ with arguments.
func substitute(typ string, params, args []string) string {
	repl := map[string]string{}
	for i, p := range params {
		repl[p] = args[i]
	}
	var b strings.Builder
	src := []byte(typ)
	for i := 0; i < len(src); {
		if isIdentStart(src, i) && (i == 0 || src[i-1] != '.') {
			e := identEnd(src, i)
			if r, ok := repl[string(src[i:e])]; ok {
				b.WriteString(r)
			} else {
				b.Write(src[i:e])
			}
			i = e
			continue
		}
		b.WriteByte(src[i])
		i++
	}
	return b.String()
}
