// Code generated by goxc from main.gox. DO NOT EDIT.

//line main.gox:1
//go:generate go run github.com/rknit/tui.gox/cmd/goxc .

package main; import gox "github.com/rknit/tui.gox/gox"

import (
	"fmt"
	"os"
	"strings"
)

type Todo struct {
	ID   int
	Text string
	Done bool
}

type action struct {
	kind string // add | toggle | clear
	id   int
	text string
}

func reducer(todos []Todo, a action) []Todo {
	switch a.kind {
	case "add":
		next := 1
		for _, t := range todos {
			next = max(next, t.ID+1)
		}
		return append(append([]Todo{}, todos...), Todo{ID: next, Text: a.text})
	case "toggle":
		out := append([]Todo{}, todos...)
		for i := range out {
			if out[i].ID == a.id {
				out[i].Done = !out[i].Done
			}
		}
		return out
	case "clear":
		var out []Todo
		for _, t := range todos {
			if !t.Done {
				out = append(out, t)
			}
		}
		return out
	}
	return todos
}

// TodoItem's parameters are its props: goxc declares TodoItemProps.
func TodoItem(gox_props_ TodoItemProps) gox.Node { return gox_TodoItem(gox_props_.Todo, gox_props_.OnToggle) }; func gox_TodoItem(todo Todo, onToggle func()) gox.Node {
	color := ""
	if todo.Done {
		color = "8"
	}
	return (
		gox.C(gox.Checkbox, gox.CheckboxProps{Checked: todo.Done, OnChange: func(bool) { onToggle() }, 
Children: gox.C(gox.Span, gox.SpanProps{Color: color, Strikethrough: todo.Done, Children: todo.Text}),
}))
}

func App() gox.Node {
	todos, dispatch := gox.UseReducer(reducer, []Todo{
		{ID: 1, Text: "Write a .gox component"},
		{ID: 2, Text: "Run goxc", Done: true},
	})
	draft, setDraft := gox.UseState("")

	left := 0
	for _, t := range todos {
		if !t.Done {
			left++
		}
	}

	submit := func(s string) {
		if strings.TrimSpace(s) != "" {
			dispatch(action{kind: "add", text: strings.TrimSpace(s)})
			setDraft("")
		}
	}

	return (
		gox.C(gox.Box, gox.BoxProps{Border: "rounded", BorderColor: "12", Title: "todos", Padding: 1, Gap: 1, Width: 60, 
Children: gox.F(gox.C(gox.Input, gox.InputProps{
Value: draft, 
OnChange: setDraft, 
OnSubmit: submit, 
Prompt: "› ", 
FocusColor: "12", 
Placeholder: "What needs to be done?", 
AutoFocus: true,
}), 
gox.C(gox.Show, gox.ShowProps{When: len(todos) > 0, Fallback: gox.C(gox.Text, gox.TextProps{Faint: true, Children: "Nothing to do."}), 
Children: gox.C(gox.Box, gox.BoxProps{
Children: gox.Map(todos, func(t Todo, _ int) gox.Node {
						return gox.K(t.ID, gox.C(TodoItem, TodoItemProps{Todo: t, OnToggle: func() { dispatch(action{kind: "toggle", id: t.ID}) }}))
					}),
}),
}), 
gox.C(gox.Divider, gox.DividerProps{Color: "8"}), 
gox.C(gox.Box, gox.BoxProps{Direction: "row", 
Children: gox.F(gox.C(gox.Text, gox.TextProps{Faint: true, Children: gox.F(left, " item(s) left")}), 
gox.C(gox.Spacer, gox.SpacerProps{}), 
gox.C(gox.Button, gox.ButtonProps{OnPress: func() { dispatch(action{kind: "clear"}) }, Children: "clear done"}),
)}),
)}))
}

func main() {
	if err := gox.Run(gox.C0(App)); err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
}

//line main.gox:52
type TodoItemProps struct { Todo Todo; OnToggle func(); }
