// Command goxc compiles .gox files (Go with XML elements) into Go.
//
// Usage:
//
//	goxc [packages]          generate foo_gox.go next to every foo.gox
//	goxc run [package] [args] generate, then go run the package
//
// Packages are directories; a trailing /... recurses. Default is ".".
// Typical use is a go:generate directive:
//
//	//go:generate go run github.com/rknit/tui.gox/cmd/goxc .
package main

import (
	"bytes"
	"errors"
	"flag"
	"fmt"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"

	"github.com/rknit/tui.gox/transpile"
)

const generatedMarker = "// Code generated by goxc"

func main() {
	flag.Usage = func() {
		fmt.Fprintln(os.Stderr, "usage: goxc [-check] [packages]\n       goxc run [package] [args...]")
		flag.PrintDefaults()
	}
	check := flag.Bool("check", false, "report files whose generated output is stale, without writing")
	verbose := flag.Bool("v", false, "print generated files")
	flag.Parse()
	args := flag.Args()

	if len(args) > 0 && args[0] == "run" {
		pkg := "."
		rest := args[1:]
		if len(rest) > 0 && !strings.HasPrefix(rest[0], "-") {
			pkg, rest = rest[0], rest[1:]
		}
		if err := generate([]string{pkg}, false, *verbose); err != nil {
			fail(err)
		}
		cmd := exec.Command("go", append([]string{"run", pkg}, rest...)...)
		cmd.Stdin, cmd.Stdout, cmd.Stderr = os.Stdin, os.Stdout, os.Stderr
		if err := cmd.Run(); err != nil {
			var ee *exec.ExitError
			if errors.As(err, &ee) {
				os.Exit(ee.ExitCode())
			}
			fail(err)
		}
		return
	}

	if len(args) == 0 {
		args = []string{"."}
	}
	if err := generate(args, *check, *verbose); err != nil {
		fail(err)
	}
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}

func generate(patterns []string, check, verbose bool) error {
	dirs, err := expand(patterns)
	if err != nil {
		return err
	}
	var errs []error
	stale := false
	for _, d := range dirs {
		s, err := generateDir(d, check, verbose)
		errs = append(errs, err)
		stale = stale || s
	}
	if err := errors.Join(errs...); err != nil {
		return err
	}
	if check && stale {
		return errors.New("goxc: generated files are stale; run goxc")
	}
	return nil
}

// expand resolves directory patterns into directories containing .gox files.
func expand(patterns []string) ([]string, error) {
	seen := map[string]bool{}
	var dirs []string
	add := func(d string) {
		if !seen[d] {
			seen[d] = true
			dirs = append(dirs, d)
		}
	}
	for _, p := range patterns {
		if strings.HasSuffix(p, ".gox") {
			add(filepath.Dir(p))
			continue
		}
		if root, ok := strings.CutSuffix(p, "/..."); ok {
			if root == "" {
				root = "."
			}
			err := filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
				if err != nil {
					return err
				}
				if d.IsDir() && path != root && (strings.HasPrefix(d.Name(), ".") || strings.HasPrefix(d.Name(), "_") || d.Name() == "testdata" || d.Name() == "vendor") {
					return filepath.SkipDir
				}
				if !d.IsDir() && strings.HasSuffix(path, ".gox") {
					add(filepath.Dir(path))
				}
				return nil
			})
			if err != nil {
				return nil, err
			}
			continue
		}
		add(p)
	}
	sort.Strings(dirs)
	return dirs, nil
}

// outputName maps foo.gox to foo_gox.go and foo_test.gox to foo_gox_test.go.
func outputName(path string) string {
	base := strings.TrimSuffix(path, ".gox")
	if b, ok := strings.CutSuffix(base, "_test"); ok {
		return b + "_gox_test.go"
	}
	return base + "_gox.go"
}

func generateDir(dir string, check, verbose bool) (stale bool, err error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return false, err
	}
	var goxFiles []string
	sources := map[string][]byte{}
	sigs := map[string]transpile.Signature{}
	for _, e := range entries {
		name := e.Name()
		path := filepath.Join(dir, name)
		switch {
		case e.IsDir():
		case strings.HasSuffix(name, ".gox"):
			src, err := os.ReadFile(path)
			if err != nil {
				return false, err
			}
			goxFiles = append(goxFiles, path)
			sources[path] = src
		case strings.HasSuffix(name, ".go"):
			src, err := os.ReadFile(path)
			if err != nil {
				return false, err
			}
			if !bytes.HasPrefix(src, []byte(generatedMarker)) {
				transpile.CollectSignatures(src, sigs)
			}
		}
	}
	if len(goxFiles) == 0 {
		return false, nil
	}

	// Pass 1: collect component signatures declared in .gox files.
	for _, path := range goxFiles {
		out, err := transpile.Transpile(sources[path], transpile.Options{Filename: path})
		if err != nil {
			return false, err
		}
		transpile.CollectSignatures(out, sigs)
	}

	// Pass 2: generate with resolved signatures.
	var errs []error
	for _, path := range goxFiles {
		out, err := transpile.Transpile(sources[path], transpile.Options{Filename: path, Components: sigs})
		if err != nil {
			errs = append(errs, err)
			continue
		}
		target := outputName(path)
		old, _ := os.ReadFile(target)
		if bytes.Equal(old, out) {
			continue
		}
		if check {
			fmt.Fprintf(os.Stderr, "stale: %s\n", target)
			stale = true
			continue
		}
		if err := os.WriteFile(target, out, 0o644); err != nil {
			errs = append(errs, err)
			continue
		}
		if verbose {
			fmt.Println(target)
		}
	}
	return stale, errors.Join(errs...)
}
